server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bone
    username: root
    password: 15813695017
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    key: 'asdfas'
    expire: 7000
    filter:
      order: -100 #Spring Security ????解决
    user:
      name: 'mi'   #???????
      password: '123456'   #??????
      roles: #???????
        - admin
        - user
#  data:
#    redis:
#      port: 6379
#      host: 192.168.10.3
#      database: 0
