server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://121.43.233.234:3306/bone
    username: root
    password: 123123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    key: 'asdfas'
    expire: 168
    filter:
      order: -100 #Spring Security ????解决
    user:
      name: 'mi'   #???????
      password: '123456'   #??????
      roles: #???????
        - admin
        - user

  mail:
    port: 465
    # 163邮箱的地址为smtp.163.com，直接填写即可
    host: smtp.126.com # smtp.163.com
    # 你申请的163邮箱
    username: oilbone@126.com # r15813695017@163.com
    # 注意密码是在开启smtp/pop3时自动生成的，记得保存一下，不然就找不到了
    password: GLhCjNzgzQXareYv  # CVmsukDabMvJyeQ6
    time: 3
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

  rabbitmq:
    addresses: 121.43.233.234
    username: oilbone
    password: 123123123
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: auto  # 改为自动确认


  data:
    redis:
      port: 6379
      host: 121.43.233.234
      database: 0
      password: 123123123

  minio:
    endpoint: 'http://121.43.233.234:9000'
    username: "oilbone"
    password: "123123123"

  weather:
    key: ac022387b6114136adc4f020305f1fa3
logging:
  level:
    root=INFO:
